### ISSUE TITLE
Requires Extension Pack

### ISSUE THREAD

**Issue by whittle** [cal/vagrant-ubuntu-precise-64#2]
With a fresh install of VirtualBox 4.1.14 for OS X, build.sh exited with status 24 and the message "The Vagrant virtual environment you are trying to package must be powered off." Then, I installed VirtualBox 4.1.14 Oracle VM VirtualBox Extension Pack, created a fresh clone of this repo and re-ran build.sh successfully. 

If this is expected behavior, please just make a note in the README that the script expects the Extension Pack to be installed.

**Comment by cal** [comment]
It doesn't require the extension pack, I've seen that same error message randomly a few times - just shutting down the machine and re-running build.sh resolved it for me.

Would be nice to figure out exactly why it happens, though.

**Comment by tigris** [comment]
I discovered yesterday that this happens if the machine you are trying to "build" already exists in some failed state. For example, i accidentally closed my laptop while it was mid-build. When I re-opened, it crapped out for whatever reasons. Then running ./build.sh again would always end in the "must be powered off" message.

I suggest just removing the VM and starting from scratch: `VBoxManage unregistervm ubuntu-precise-64 --delete`

Personally, i've added this to my build.sh script at the top of the script, along with removing the custom folder and custom.iso file, so each build.sh run is completely from scratch, except for downloading the official iso release file.

**Comment by cal** [comment]
Hmm, that's probably better for most people, why don't you send a pull request?

We should probably delete the VM after generating the base box, too?
